[project]
name = "production-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rikmondal67", email = "mondalrik67@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "llama-parse>=0.6.94",
    "pinecone>=9.1.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
    "voyageai>=0.5.0",
]

[project.scripts]
production-rag = "production_rag:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
